x-common-env: &common-env
  AWS_PROFILE: local-dev
  AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
  AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
  AWS_DEFAULT_REGION: us-west-2
  DYNAMODB_ENDPOINT_URL: http://dynamodb-local:8000
  MOUSOUTRADE_CONFIG_FILE: /app/config/Portfolio_US_Positions_Jan-21-2025.json
  MOUSOUTRADE_STAGE: Alpha

x-common-dependencies: &common-dependencies
  - dynamodb-local
  - s3-local

services:
  app:
    build:
      context: ../
      dockerfile: ./app/build-app-image.Dockerfile
    image: mousoutrade-app
    container_name: app
    environment:
      <<: *common-env
    depends_on:
      - dynamodb-local
    stdin_open: true  # Keep the container open for interactive mode
    tty: true  # Allocate a pseudo-TTY
  website:
    build:
      context: ../
      dockerfile: ./website/website.Dockerfile
    image: mousoutrade-website
    container_name: web
    ports:
      - '5000:5000'
    environment:
      <<: *common-env
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    environment:
      <<: *common-env

  s3-local:
    image: minio/minio
    container_name: s3-local
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      <<: *common-env
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data


