name: ${PROJECT_NAME}
networks:
  network:
    name: ${PROJECT_NAME}-${MOUSOUTRADE_VERSION}
    driver: bridge

services:
  website:
    image: ${DOCKERHUB_USERNAME}/${WEBSITE_IMAGE_NAME}:${MOUSOUTRADE_VERSION}
    container_name: ${WEBSITE_CONTAINER_NAME}
    hostname: website
    ports:
      - '${WEBSITE_PORT}:${WEBSITE_PORT}'
    depends_on:
      - dynamodb-local
      - app
    networks:
      - network

  app:
    image: ${DOCKERHUB_USERNAME}/${APP_IMAGE_NAME}:${MOUSOUTRADE_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    hostname: app
    depends_on:
      - dynamodb-local
    networks:
      - network

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: ${DYNAMODB_CONTAINER_NAME}
    hostname: dynamodb-local
    ports:
      - '${DYNAMODB_PORT}:${DYNAMODB_PORT}'
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    networks:
      - network